name: Assert branch naming rules
on:
  push:
    branches-ignore:
      - main

jobs:
  assert-branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^feature\/.+$' 
          ignore: main
