name: Assert branch naming rules
on: 
  create:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  assert-branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        if: github.event_name == 'pull_request' || github.event.pull_request == null
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^feature\/.+$' 
          ignore: main
