name: Assert branch naming rules
on:
  pull_request_target:
    branches:
      - main

jobs:
  assert-branch-naming-rules:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH_NAME" =~ ^feature\/.+$ ]]; then
            echo "✅ Branch name is valid"
          else
            echo "❌ Invalid branch name: $BRANCH_NAME"
            exit 1
          fi
