name: Assert branch naming rules
on:
  pull_request_target:
    branches:
      - main

jobs:
  assert-branch-naming-rules:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^feature\/.+$' 
          ignore: main
