name: Deploy the app

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: Deploy the app
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Deploy on Netlofy
        # uses: jsmrcaga/action-netlify-deploy@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_alias: ${{ github.event.pull_request.head.ref }}
        run: netlify deploy

    #   - name: Status check
    #     uses: Sibz/github-status-action@v1.1.1
    #     with:
    #       authToken: ${{ secrets.GITHUB_TOKEN }}
    #       context: Netlify preview
    #       state: success
    #       target_url: ${{ env.NETLIFY_PREVIEW_URL }}
