name: Assert Branch Naming Rules
on: 
  push:
    branches-ignore:
      - main
  create:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  assert-branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^feature\/.+$' 
          ignore: main
